#include <bits/stdc++.h>
using namespace std;

typedef unsigned long long ull;
bool GLOBAL_PRINT_FLAG = true;

/// Crap ton of hardcoded data
/// Most of it was generated by this file!!!

const char move_names[][3] = {"U","D","F","B","L","R","U2","D2","F2","B2","L2","R2","U'","D'","F'","B'","L'","R'"};

const unsigned centers[] = {4,49,25,31,22,28};

const unsigned edgelist[][2] = {{7,13}, {5,16}, {1,19}, {3,10}, {26,27}, {30,29}, {32,21}, {24,23}, {46,37}, {50,40}, {52,43}, {48,34}};
const unsigned vertlist[][3] = {{8,14,15}, {2,18,17}, {0,20,9}, {6,12,11}, {45,36,35}, {47,38,39}, {53,42,41}, {51,44,33}};

unsigned edgemap[36] = {0,0,0,2,3,1,0,0,8,10,11,9,16,24,0,8,7,4,18,26,24,0,6,5,19,27,23,22,0,6,17,25,20,21,22,0};
unsigned vertmap[8] = {3,0,2,1,4,5,7,6};

// [move, index] = index
unsigned edgemovetable[18][12] = {{3,0,1,2,4,5,6,7,8,9,10,11},{0,1,2,3,4,5,6,7,9,10,11,8},{4,1,2,3,8,5,6,0,7,9,10,11},{0,1,6,3,4,2,10,7,8,9,5,11},{0,1,2,7,4,5,3,11,8,9,10,6},{0,5,2,3,1,9,6,7,8,4,10,11},{2,3,0,1,4,5,6,7,8,9,10,11},
                                  {0,1,2,3,4,5,6,7,10,11,8,9},{8,1,2,3,7,5,6,4,0,9,10,11},{0,1,10,3,4,6,5,7,8,9,2,11},{0,1,2,11,4,5,7,6,8,9,10,3},{0,9,2,3,5,4,6,7,8,1,10,11},{1,2,3,0,4,5,6,7,8,9,10,11},{0,1,2,3,4,5,6,7,11,8,9,10},
                                  {7,1,2,3,0,5,6,8,4,9,10,11},{0,1,5,3,4,10,2,7,8,9,6,11},{0,1,2,6,4,5,11,3,8,9,10,7},{0,4,2,3,9,1,6,7,8,5,10,11}};
unsigned vertmovetable[18][8] = {{3,0,1,2,4,5,6,7},{0,1,2,3,5,6,7,4},{5,1,2,0,3,4,6,7},{0,2,7,3,4,5,1,6},{0,1,3,4,7,5,6,2},{1,6,2,3,4,0,5,7},{2,3,0,1,4,5,6,7},{0,1,2,3,6,7,4,5},{4,1,2,5,0,3,6,7},{0,7,6,3,4,5,2,1},{0,1,4,7,2,5,6,3},
                                 {6,5,2,3,4,1,0,7},{1,2,3,0,4,5,6,7},{0,1,2,3,7,4,5,6},{3,1,2,4,5,0,6,7},{0,6,1,3,4,5,7,2},{0,1,7,2,3,5,6,4},{5,0,2,3,4,6,1,7}};

// [move, index, orientation] = orientation;
unsigned edgemoveorient[18][12][2] = {{{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1}},{{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1}},
                                      {{1,0},{0,1},{0,1},{0,1},{1,0},{0,1},{0,1},{1,0},{1,0},{0,1},{0,1},{0,1}},{{0,1},{0,1},{1,0},{0,1},{0,1},{1,0},{1,0},{0,1},{0,1},{0,1},{1,0},{0,1}},
                                      {{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1}},{{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1}},
                                      {{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1}},{{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1}},
                                      {{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1}},{{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1}},
                                      {{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1}},{{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1}},
                                      {{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1}},{{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1}},
                                      {{1,0},{0,1},{0,1},{0,1},{1,0},{0,1},{0,1},{1,0},{1,0},{0,1},{0,1},{0,1}},{{0,1},{0,1},{1,0},{0,1},{0,1},{1,0},{1,0},{0,1},{0,1},{0,1},{1,0},{0,1}},
                                      {{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1}},{{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1},{0,1}}};
unsigned vertmoveorient[18][8][3] = {{{0,2,1},{0,2,1},{0,2,1},{0,2,1},{0,1,2},{0,1,2},{0,1,2},{0,1,2}},{{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,2,1},{0,2,1},{0,2,1},{0,2,1}},{{2,1,0},{0,1,2},{0,1,2},{2,1,0},{2,1,0},{2,1,0},{0,1,2},{0,1,2}},
                                     {{0,1,2},{2,1,0},{2,1,0},{0,1,2},{0,1,2},{0,1,2},{2,1,0},{2,1,0}},{{0,1,2},{0,1,2},{1,0,2},{1,0,2},{1,0,2},{0,1,2},{0,1,2},{1,0,2}},{{1,0,2},{1,0,2},{0,1,2},{0,1,2},{0,1,2},{1,0,2},{1,0,2},{0,1,2}},
                                     {{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2}},{{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2}},{{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2}},
                                     {{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2}},{{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2}},{{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,1,2}},
                                     {{0,2,1},{0,2,1},{0,2,1},{0,2,1},{0,1,2},{0,1,2},{0,1,2},{0,1,2}},{{0,1,2},{0,1,2},{0,1,2},{0,1,2},{0,2,1},{0,2,1},{0,2,1},{0,2,1}},{{2,1,0},{0,1,2},{0,1,2},{2,1,0},{2,1,0},{2,1,0},{0,1,2},{0,1,2}},
                                     {{0,1,2},{2,1,0},{2,1,0},{0,1,2},{0,1,2},{0,1,2},{2,1,0},{2,1,0}},{{0,1,2},{0,1,2},{1,0,2},{1,0,2},{1,0,2},{0,1,2},{0,1,2},{1,0,2}},{{1,0,2},{1,0,2},{0,1,2},{0,1,2},{0,1,2},{1,0,2},{1,0,2},{0,1,2}}};

unsigned raw_edgesymmove[4][12];
unsigned raw_vertsymmove[4][8];
unsigned raw_edgesymorient[4][12][2];
unsigned raw_vertsymorient[4][8][3];

unsigned edgesymmove[48][12];
unsigned vertsymmove[48][8];
unsigned edgesymorient[48][12][2];
unsigned vertsymorient[48][8][3];


char input[55]; // global for generation function
unsigned translate[256];
struct cube
{
    static cube solved, twisted;

    ull edges=0, verts=0;

    // Loading
    static ull translate_edge(int x, int y) { return edgemap[6*x+y]; }
    static ull translate_vert(int x, int y, int z)
    {
        int cx = min(x, min(y,z));
        int cz = max(x, max(y,z));
        int cy = x+y+z-cx-cz;
        int base = vertmap[4*(cx&1)+2*(cy&1)+(cz&1)];
        if (x<y && x<z) return base;
        if (y<z) return base|8;
        return base|16;
    }
    static cube from_input()
    {
        for (int i=0; i<54; i++) scanf("%s", input+i);
        for (int i=0; i<6; i++) translate[(int)'0'+i] = i;
//        for (int i=0; i<6; i++) translate[(int)input[centers[i]]] = inception[i];
        for (int i=0; i<54; i++) input[i] = translate[(int)input[i]];
        ull edges=0, verts=0;
        for (int i=0; i<12; i++) edges |= translate_edge(input[edgelist[i][0]], input[edgelist[i][1]])<<(5*i);
        for (int i=0; i< 8; i++) verts |= translate_vert(input[vertlist[i][0]], input[vertlist[i][1]], input[vertlist[i][2]])<<(5*i);

        // Sanity
        int cnt[12] = {0};
        for (int i=0; i<12; i++) cnt[(edges>>5*i)&15]++;
        for (int i=0; i<12; i++) assert(cnt[i] == 1);
        for (int i=0; i<12; i++) cnt[i] = 0;
        for (int i=0; i<8; i++) cnt[(verts>>5*i)&7]++;
        for (int i=0; i<8; i++) assert(cnt[i] == 1);
        return cube(edges, verts);

    }
    cube(ull edges, ull verts) : edges(edges), verts(verts) {}
    static cube random_cube(int scramble=30, int seed=-1)
    {
        seed += time(NULL);
        if (GLOBAL_PRINT_FLAG) { printf("Random cube with seed "); cout << seed << '\n'; }
        srand(seed);
        for (int i=0; i<100; i++) rand();

        ull edges = solved.edges;
        ull verts = solved.verts;
        for (int i=0; i<scramble; i++)
        {
            cube next = cube(edges, verts).make_move(rand()%18);
            edges = next.edges;
            verts = next.verts;
        }
        return cube(edges, verts);
    }

    // Debug
    void print(void) const
    {
        if (!GLOBAL_PRINT_FLAG) return;
//        printf("%llx %llx\n", edges, verts);
//        cout << bitset<64>(edges) << '\n' << bitset<64>(verts) << '\n';

//        printf("0000");
//        for (int i=11; i>=0; --i) cout << ' ' << bitset<5>(edges>>(5*i));
//        printf("\n000000000000000000000000");
//        for (int i=7; i>=0; --i) cout << ' ' << bitset<5>(verts>>(5*i));
//        putchar('\n');

        printf("edges:");
        for (int i=11; i>=0; --i) printf(" %d:%d", (edges>>(5*i+4))&1, (edges>>5*i)&15);
        printf("\nverts:");
        for (int i=7; i>=0; --i) printf(" %d:%d", (verts>>(5*i+3))&3, (verts>>5*i)&7);
        putchar('\n');
    }
    void print(const cube &other) const
    {
        if (!GLOBAL_PRINT_FLAG) return;
        printf("A eo:");
        for (int i=11; i>=0; --i) printf(" %d", (edges>>(5*i+4))&1);
        printf("\nB eo:");
        for (int i=11; i>=0; --i) printf(" %d", (other.edges>>(5*i+4))&1);
        printf("\nA ep:");
        for (int i=11; i>=0; --i) printf(" %d", (edges>>5*i)&15);
        printf("\nB ep:");
        for (int i=11; i>=0; --i) printf(" %d", (other.edges>>5*i)&15);
        printf("\nA vo:");
        for (int i=11; i>=0; --i) printf(" %d", (verts>>(5*i+3))&3);
        printf("\nB vo:");
        for (int i=11; i>=0; --i) printf(" %d", (other.verts>>(5*i+3))&3);
        printf("\nA vp:");
        for (int i=11; i>=0; --i) printf(" %d", (verts>>5*i)&7);
        printf("\nB vp:");
        for (int i=11; i>=0; --i) printf(" %d", (other.verts>>5*i)&7);
        putchar('\n');
    }
    void print_net(void)
    {

    }
    bool operator==(const cube& other) const
    {
        return edges == other.edges && verts == other.verts;
    }


    // Move making
    cube make_move(int moveid) const
    {
        ull new_edges=0, new_verts=0;
        for (int i=0; i<12; i++)
        {
            const auto source = (edges >> 5*i) & 31;
            const auto pieceid = source&15;
            const auto piecerot = source>>4;
            new_edges |= (ull)(pieceid | (edgemoveorient[moveid][i][piecerot]<<4)) << 5*edgemovetable[moveid][i];
        }
        for (int i=0; i<8; i++)
        {
            const auto source = (verts >> 5*i) & 31;
            const auto pieceid = source&7;
            const auto piecerot = source>>3;
            new_verts |= (ull)(pieceid | (vertmoveorient[moveid][i][piecerot]<<3)) << 5*vertmovetable[moveid][i];
        }
        return cube(new_edges, new_verts);
    }

    // Raw symmetry moving
    cube make_raw_symmetry(int symid) const
    {
        ull new_edges=0, new_verts=0;
        for (int i=0; i<12; i++)
        {
            const auto source = (edges >> 5*i) & 31;
            const auto pieceid = source&15;
            const auto piecerot = source>>4;
            assert(pieceid<12);
            assert(piecerot < 3);
            const auto newloc = raw_edgesymmove[symid][i];
            const auto newrot = raw_edgesymorient[symid][i][piecerot];
            new_edges |= (ull)(pieceid | (newrot<<4)) << 5*newloc;
        }
        for (int i=0; i<8; i++)
        {
            const auto source = (verts >> 5*i) & 31;
            const auto pieceid = source&7;
            const auto piecerot = source>>3;
            assert(piecerot < 3);
            const auto newloc = raw_vertsymmove[symid][i];
            const auto newrot = raw_vertsymorient[symid][i][piecerot];
            new_verts |= (ull)(pieceid | (newrot<<3)) << 5*newloc;
        }
        return cube(new_edges, new_verts);
    }

    cube get_canonical(void) const
    {
        cube ret(LLONG_MAX, LLONG_MAX);
        for (int s=0; s<48; s++)
        {
            cube test = make_symmetry(s);
            if (test.edges < ret.edges || (test.edges == ret.edges && test.verts < ret.verts)) ret = test;
        }
        return ret;
    }

    // Full symmetry moving
#define URF3 16
#define F2 8
#define U4 2
#define LR2 1
    cube make_symmetry(int symid) const
    {
        ull new_edges=0, new_verts=0;
        for (int i=0; i<12; i++)
        {
            const auto source = (edges >> 5*i) & 31;
            const auto pieceid = source&15;
            const auto piecerot = source>>4;
            assert(pieceid<12);
            assert(piecerot < 3);
            const auto newloc = edgesymmove[symid][i];
            const auto newid = edgesymmove[symid][pieceid];
            const auto newrot = edgesymorient[symid][i][piecerot];
            new_edges |= (ull)(newid | (newrot<<4)) << 5*newloc;
        }
        for (int i=0; i<8; i++)
        {
            const auto source = (verts >> 5*i) & 31;
            const auto pieceid = source&7;
            const auto piecerot = source>>3;
            assert(piecerot < 3);
            const auto newloc = vertsymmove[symid][i];
            const auto newid = vertsymmove[symid][pieceid];
            const auto newrot = vertsymorient[symid][i][piecerot];
            new_verts |= (ull)(newid | (newrot<<3)) << 5*newloc;
        }
        return cube(new_edges, new_verts);
    }
}
cube::solved(0x5a928398a418820, 0x398a418820),
cube::twisted(0x5a928398a418820, 0x7b9ac5a928);

/*
Indices
          0  1  2
          3  4  5
          6  7  8
 9 10 11 12 13 14 15 16 17 18 19 20
21 22 23 24 25 26 27 28 29 30 31 32
33 34 35 36 37 38 39 40 41 42 43 44
         45 46 47
         48 49 50
         51 52 53

Solved
      0 0 0
      0 0 0
      0 0 0
4 4 4 2 2 2 5 5 5 3 3 3
4 4 4 2 2 2 5 5 5 3 3 3
4 4 4 2 2 2 5 5 5 3 3 3
      1 1 1
      1 1 1
      1 1 1

Twist
      4 0 5
      0 0 0
      4 0 5
3 4 2 0 2 0 2 5 3 0 3 0
4 4 4 2 2 2 5 5 5 3 3 3
3 4 2 1 2 1 2 5 3 1 3 1
      4 1 5
      1 1 1
      4 1 5

Priorities: Top/bottom, then Front/back, and then Left/right, labelled 1 to 6

Edge list: 7/13, 3/10, 1/19, 5/16, 26/27, 30/29, 32/21, 24/23, 46/37, 50/40, 52/43, 48/34
Vertex list: 8/14/15, 2/18/17, 0/20/9, 6/12/11, 47/38/39, 53/42/41, 51/44/33, 45/36/35
Edges take 1 orientation bit + 4 index bits. Orientation 1 is priority mismatch
Vertices take 2 orientation bits + 3 index bits. Orietation is how far down #1 priority is
*/

int tmp(int x, int y, int z) { return 4*(x&1)+2*(y&1)+(z&1); }
int tmp2(int x, int y) { return x*6+y; }
void map_generation()
{
    cube start = cube::from_input();
    for (int i=0; i<12; i++) edgemap[tmp2(input[edgelist[i][0]], input[edgelist[i][1]])] = i;
    for (int i=0; i<12; i++) edgemap[tmp2(input[edgelist[i][1]], input[edgelist[i][0]])] = i|16;
    for (int i=0; i<8; i++) vertmap[tmp(input[vertlist[i][0]], input[vertlist[i][1]], input[vertlist[i][2]])] = i;
    for (int i=0; i<36; i++) printf("%d,",edgemap[i]);
    putchar('\n');
    for (int i=0; i<8; i++) printf("%d,",vertmap[i]);
    putchar('\n');
}


void table_generation(void)
{
    // Load test rotations
    freopen("single_rotations.txt", "r", stdin);
    const cube UDFBLR[] = {cube::from_input(),cube::from_input(),cube::from_input(),cube::from_input(),cube::from_input(),cube::from_input()};
    const cube UDFBLR_twist[] = {cube::from_input(),cube::from_input(),cube::from_input(),cube::from_input(),cube::from_input(),cube::from_input()};

    // Compute edge stuff for 90 degree clockwise
    for (int t=0; t<6; t++) for (int i=0; i<12; i++)
    {
        auto source = (UDFBLR[t].edges >> 5*i)&31;
        auto pieceid = source&15;
        auto piecerot = source>>4;
        edgemovetable[t][pieceid] = i;
        edgemoveorient[t][pieceid][0] = piecerot;
        edgemoveorient[t][pieceid][1] = !piecerot;
    }

    // Compound edge turns
    for (int q=1; q<3; q++) for (int t=0; t<6; t++) for (int i=0; i<12; i++)
    {
        edgemovetable[6*q+t][i] = edgemovetable[6*(q-1)+t][edgemovetable[t][i]];
        edgemoveorient[6*q+t][i][0] = edgemoveorient[6*(q-1)+t][edgemovetable[t][i]][edgemoveorient[t][i][0]];
        edgemoveorient[6*q+t][i][1] = !edgemoveorient[6*q+t][i][0];
    }

    // Compute vert stuff for 90 degree clockwise
    for (int t=0; t<6; t++) for (int i=0; i<8; i++)
    {
        auto source = (UDFBLR[t].verts >> 5*i)&31;
        auto source_twist = (UDFBLR_twist[t].verts >> 5*i)&31;
        auto pieceid = source&7;
        auto piecerot = source>>3;
        auto piecerot_twist = source_twist>>3;
        vertmovetable[t][pieceid] = i;
        vertmoveorient[t][pieceid][0] = piecerot;
        vertmoveorient[t][pieceid][1] = piecerot_twist;
        vertmoveorient[t][pieceid][2] = 3 - piecerot - piecerot_twist;
    }

    // Compound vert turns
    for (int q=1; q<3; q++) for (int t=0; t<6; t++) for (int i=0; i<8; i++)
    {
        vertmovetable[6*q+t][i] = vertmovetable[6*(q-1)+t][vertmovetable[t][i]];
        for (int j=0; j<3; j++) vertmoveorient[6*q+t][i][j] = vertmoveorient[6*(q-1)+t][vertmovetable[t][i]][vertmoveorient[t][i][j]];
    }

    // Output
    puts("edgemovetable");
    printf("{"); for (int t=0; t<18; t++) {
        printf(t?",{":"{"); for (int i=0; i<12; i++) printf(i?",%d":"%d", edgemovetable[t][i]); printf("}");
    } puts("}");
    puts("edgemoveorient");
    printf("{"); for (int t=0; t<18; t++) {
        printf(t?",{":"{"); for (int i=0; i<12; i++) printf(i?",{%d,%d}":"{%d,%d}", edgemoveorient[t][i][0], edgemoveorient[t][i][1]); printf("}");
    } puts("}");

    puts("vertmovetable");
    printf("{"); for (int t=0; t<18; t++) {
        printf(t?",{":"{"); for (int i=0; i<8; i++) printf(i?",%d":"%d", vertmovetable[t][i]); printf("}");
    } puts("}");
    puts("vertmoveorient");
    printf("{"); for (int t=0; t<18; t++) {
        printf(t?",{":"{"); for (int i=0; i<8; i++) printf(i?",{%d,%d,%d}":"{%d,%d,%d}", vertmoveorient[t][i][0], vertmoveorient[t][i][1], vertmoveorient[t][i][2]); printf("}");
    } puts("}");
}

void print_raw_symmetries()
{
    puts("raw_edgesymmove");
    printf("{"); for (int t=0; t<4; t++) {
        printf(t?",{":"{"); for (int i=0; i<12; i++) printf(i?",%u":"%u", raw_edgesymmove[t][i]); printf("}");
    } puts("}");
    puts("raw_edgesymorient");
    printf("{"); for (int t=0; t<4; t++) {
        printf(t?",{":"{"); for (int i=0; i<12; i++) printf(i?",{%u,%u}":"{%u,%u}", raw_edgesymorient[t][i][0], raw_edgesymorient[t][i][1]); printf("}");
    } puts("}");

    puts("raw_vertsymmove");
    printf("{"); for (int t=0; t<4; t++) {
        printf(t?",{":"{"); for (int i=0; i<8; i++) printf(i?",%u":"%u", raw_vertsymmove[t][i]); printf("}");
    } puts("}");
    puts("raw_vertsymorient");
    printf("{"); for (int t=0; t<4; t++) {
        printf(t?",{":"{"); for (int i=0; i<8; i++) printf(i?",{%u,%u,%u}":"{%u,%u,%u}", raw_vertsymorient[t][i][0], raw_vertsymorient[t][i][1], raw_vertsymorient[t][i][2]); printf("}");
    } puts("}");
}

void  print_full_symmetries()
{
    puts("edgesymmove");
    printf("{"); for (int t=0; t<48; t++) {
        printf(t?",{":"{"); for (int i=0; i<12; i++) printf(i?",%u":"%u", edgesymmove[t][i]); printf("}");
    } puts("}");
    puts("edgesymorient");
    printf("{"); for (int t=0; t<48; t++) {
        printf(t?",{":"{"); for (int i=0; i<12; i++) printf(i?",{%u,%u}":"{%u,%u}", edgesymorient[t][i][0], edgesymorient[t][i][1]); printf("}");
    } puts("}");

    puts("vertsymmove");
    printf("{"); for (int t=0; t<48; t++) {
        printf(t?",{":"{"); for (int i=0; i<8; i++) printf(i?",%u":"%u", vertsymmove[t][i]); printf("}");
    } puts("}");
    puts("vertsymorient");
    printf("{"); for (int t=0; t<48; t++) {
        printf(t?",{":"{"); for (int i=0; i<8; i++) printf(i?",{%u,%u,%u}":"{%u,%u,%u}", vertsymorient[t][i][0], vertsymorient[t][i][1], vertsymorient[t][i][2]); printf("}");
    } puts("}");
}

void symmetry_generation()
{
    // Load test symmetries
    freopen("symmetries.txt", "r", stdin);
    const cube URF3F2U4LR2[] = {cube::from_input(),cube::from_input(),cube::from_input(),cube::from_input()};
    const cube URF3F2U4LR2_twist[] = {cube::from_input(),cube::from_input(),cube::from_input(),cube::from_input()};

    // Compute edge stuff for base symmetries
    for (int t=0; t<4; t++) for (int i=0; i<12; i++)
    {
        auto source = (URF3F2U4LR2[t].edges >> 5*i)&31;
        auto pieceid = source&15;
        auto piecerot = source>>4;
        raw_edgesymmove[t][pieceid] = i;
        raw_edgesymorient[t][pieceid][0] = piecerot;
        raw_edgesymorient[t][pieceid][1] = !piecerot;
    }


    // Compute vert stuff for base symmetries
    for (int t=0; t<4; t++) for (int i=0; i<8; i++)
    {
        auto source = (URF3F2U4LR2[t].verts >> 5*i)&31;
        auto source_twist = (URF3F2U4LR2_twist[t].verts >> 5*i)&31;
        auto pieceid = source&7;
        auto piecerot = source>>3;
        auto piecerot_twist = source_twist>>3;
        raw_vertsymmove[t][pieceid] = i;
        raw_vertsymorient[t][pieceid][0] = piecerot;
        raw_vertsymorient[t][pieceid][1] = piecerot_twist;
        raw_vertsymorient[t][pieceid][2] = 3 - piecerot - piecerot_twist;
    }

    // Compound into the 48 symmetries
    for (int t=0; t<48; t++)
    {
        cube cur1 = cube::solved;
        cube cur2 = cube::twisted;
        int tt = t;
        int x1234[] = {tt>>4, (tt>>3)&1, (tt>>1)&3, tt&1};
        for (int s=3; s>=0; --s) for (int l=0; l<x1234[s]; l++)
        {
            cur1 = cur1.make_raw_symmetry(s);
            cur2 = cur2.make_raw_symmetry(s);
        }

        for (int i=0; i<12; i++)
        {
            auto source = (cur1.edges >> 5*i)&31;
            auto pieceid = source&15;
            auto piecerot = source>>4;
            edgesymmove[t][pieceid] = i;
            edgesymorient[t][pieceid][0] = piecerot;
            edgesymorient[t][pieceid][1] = !piecerot;
        }

        for (int i=0; i<8; i++)
        {
            auto source = (cur1.verts >> 5*i)&31;
            auto source_twist = (cur2.verts >> 5*i)&31;
            auto pieceid = source&7;
            auto piecerot = source>>3;
            auto piecerot_twist = source_twist>>3;
            vertsymmove[t][pieceid] = i;
            vertsymorient[t][pieceid][0] = piecerot;
            vertsymorient[t][pieceid][1] = piecerot_twist;
            vertsymorient[t][pieceid][2] = 3 - piecerot - piecerot_twist;
        }
    }

    // Output
//    print_raw_symmetries();
//    print_full_symmetries();
//    cube::solved.print();
//    cube::twisted.print();
}


void sanity_moves(void)
{
    puts("Sanity testing moves");
    freopen("single_rotations.txt", "r", stdin);
    const cube UDFBLR[] = {cube::from_input(),cube::from_input(),cube::from_input(),cube::from_input(),cube::from_input(),cube::from_input()};
    const cube UDFBLR_twist[] = {cube::from_input(),cube::from_input(),cube::from_input(),cube::from_input(),cube::from_input(),cube::from_input()};

    for (int t=0; t<6; t++)
    {
        cube test = cube::solved.make_move(t);
        printf("Test %d = %d\n", t, test == UDFBLR[t]);
        assert(test == UDFBLR[t]);
    }
    for (int t=0; t<6; t++)
    {
        cube test = cube::twisted.make_move(t);
        printf("Test %d = %d\n", t+6, test == UDFBLR_twist[t]);
        assert(test == UDFBLR_twist[t]);
    }
}

bool test_helper(int testid, const cube &a, const cube &b)
{
    if (GLOBAL_PRINT_FLAG) printf("Test %c = %d\n", testid>=0 ? 'A'+testid : 'a'-testid-1, a == b);
    a.print(b);
    if (GLOBAL_PRINT_FLAG) putchar('\n');
    return a == b;
}
void sanity_symmetry(void)
{
    puts("Sanity testing symmetry");
    freopen("single_rotations.txt", "r", stdin);
    const cube UDFBLR[] = {cube::from_input(),cube::from_input(),cube::from_input(),cube::from_input(),cube::from_input(),cube::from_input()};
    const cube UDFBLR_twist[] = {cube::from_input(),cube::from_input(),cube::from_input(),cube::from_input(),cube::from_input(),cube::from_input()};

    /// All these pass
//    GLOBAL_PRINT_FLAG = false;
//    int success = 0;
//    for (int i=0; i<10000; i++)
//    {
//        cube cur = cube::random_cube(30, i);
//        cube next = cur;
//        next = next.make_symmetry(U4);
//        next = next.make_symmetry(F2);
//        next = next.make_symmetry(U4);
//        next = next.make_symmetry(F2);
//        success += test_helper(i, cur, next);
//    }
//    printf("Successes: %d\n", success);

    auto a = UDFBLR[0].get_canonical();
    auto b = UDFBLR[2].get_canonical();
    test_helper(2, a, b);

    return;

    putchar('\n');
    puts("Manual testing");
    putchar('\n');
    test_helper(-1, UDFBLR[0].make_symmetry(U4), UDFBLR[0]);
    test_helper(-2, UDFBLR[1].make_symmetry(U4), UDFBLR[1]);
    test_helper(-3, UDFBLR[2].make_symmetry(U4), UDFBLR[5]);
    test_helper(-4, UDFBLR[3].make_symmetry(U4), UDFBLR[4]);
    test_helper(-5, UDFBLR[4].make_symmetry(U4), UDFBLR[2]);
    test_helper(-6, UDFBLR[5].make_symmetry(U4), UDFBLR[3]);

    putchar('\n');
    puts("Automatic testing");
    putchar('\n');

    cube standard(0,0);
    for (int t=0; t<6; t++)
    {
        cube min(LLONG_MAX, LLONG_MAX);
        for (int s=0; s<48; s++)
        {
            cube test = UDFBLR[t].make_symmetry(s);
            if (test.edges < min.edges || (test.edges == min.edges && test.verts < min.verts)) min = test;
        }
        if (!t)
        {
            standard = min;
            standard.print();
        }
        else test_helper(t, standard, min);
    }
    for (int t=0; t<6; t++)
    {
        cube min(LLONG_MAX, LLONG_MAX);
        for (int s=0; s<48; s++)
        {
            cube test = UDFBLR_twist[t].make_symmetry(s);
            if (test.edges < min.edges || (test.edges == min.edges && test.verts < min.verts)) min = test;
        }
        if (!t)
        {
            standard = min;
            standard.print();
        }
        else test_helper(t+6, standard, min);
    }
}

int main(void)
{
//    cube start(IN);
//    start.print();

//    map_generation();

//    table_generation();

    symmetry_generation();

//    sanity_moves();
    sanity_symmetry();
    return 0;
}
